config:
  longkey: true
dotfiles:
  d_jenv:
    src: jenv
    dst: ~/.jenv
    link: link
  d_nvm:
    src: nvm
    dst: ~/.nvm
    link: link
  d_pyenv:
    src: pyenv
    dst: ~/.pyenv
    link: link
  d_vim:
    src: vim
    dst: ~/.vim
    link: link
  f_alacrittyyml:
    src: alacritty.yml
    dst: ~/.alacritty.yml
    link: link
  f_ctags:
    src: ctags
    dst: ~/.ctags
    link: link
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_tmuxconfig:
    src: tmux/.tmux.conf
    dst: ~/.tmux.conf
    link: link
  f_tmuxconfiglocal:
    src: tmux/.tmux.conf.local
    dst: ~/.tmux.conf.local
  f_urlview:
    src: urlview
    dst: ~/.urlview
    link: link
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    link: link
  f_zprofile:
    src: zprofile
    dst: ~/.zprofile
    link: link
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    link: link
profiles:
  debian:
    dotfiles:
    - d_jenv
    - d_nvm
    - d_pyenv
    - d_vim
    - f_alacrittyyml
    - f_ctags
    - f_gitconfig
    - f_tmuxconfig
    - f_tmuxconfiglocal
    - f_urlview
    - f_vimrc
    - f_zshrc
  macos:
    dotfiles:
    - d_jenv
    - d_nvm
    - d_pyenv
    - d_vim
    - f_alacrittyyml
    - f_ctags
    - f_gitconfig
    - f_tmuxconfig
    - f_tmuxconfiglocal
    - f_urlview
    - f_vimrc
    - f_zprofile
    - f_zshrc
