config:
  longkey: true
dotfiles:
  d_vim:
    src: vim
    dst: ~/.vim
    link: link
  f_ctags:
    src: ctags
    dst: ~/.ctags
    link: link
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_tmuxconfig:
    src: tmux/.tmux.conf
    dst: ~/.tmux.conf
    link: link
  f_tmuxconfiglocal:
    src: tmux/.tmux.conf.local
    dst: ~/.tmux.conf.local
  f_urlview:
    src: urlview
    dst: ~/.urlview
    link: link
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    link: link
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    link: link
profiles:
  debian:
    dotfiles:
    - d_vim
    - f_ctags
    - f_gitconfig
    - f_tmuxconfig
    - f_tmuxconfiglocal
    - f_urlview
    - f_vimrc
    - f_zshrc
  macos:
    dotfiles:
    - d_vim
    - f_ctags
    - f_gitconfig
    - f_tmuxconfig
    - f_tmuxconfiglocal
    - f_urlview
    - f_vimrc
    - f_zshrc
